"""
Code Generator.
Walks the AST and emits two outputs:
  1. A human-readable "assembly-like" IR (Intermediate Representation)
  2. Runnable Python code that simulates execution of the compiled C program

The IR is useful for understanding compilation; the Python backend lets
the program actually execute.
"""

from typing import List, Dict, Optional
from .ast_nodes import *
import re


#  IR Instruction set 

class IRGen:
    """Generates a simple 3-address code / stack-machine IR."""

    def __init__(self):
        self.instructions: List[str] = []
        self.temp_count = 0
        self.label_count = 0
        self.string_pool: Dict[str, str] = {}  # label -> value

    def emit(self, instr: str):
        self.instructions.append(instr)

    def new_temp(self) -> str:
        t = f"t{self.temp_count}"
        self.temp_count += 1
        return t

    def new_label(self) -> str:
        l = f"L{self.label_count}"
        self.label_count += 1
        return l

    def generate(self, program: Program) -> str:
        self.emit("; === C Compiler IR Output ===")
        self.emit("; Generated by PyCCompiler v1.0")
        self.emit("")
        for decl in program.declarations:
            self.gen_node(decl)
        return "\n".join(self.instructions)

    def gen_node(self, node: ASTNode) -> Optional[str]:
        method = f"gen_{type(node).__name__}"
        gen = getattr(self, method, None)
        if gen:
            return gen(node)
        return None

    def gen_Program(self, node: Program):
        for decl in node.declarations:
            self.gen_node(decl)

    def gen_FunctionDef(self, node: FunctionDef):
        params = ", ".join(p.name for p in node.params)
        self.emit(f"\nFUNC {node.return_type.name} {node.name}({params}):")
        self.gen_node(node.body)
        self.emit(f"END_FUNC {node.name}")

    def gen_Block(self, node: Block):
        for stmt in node.statements:
            self.gen_node(stmt)

    def gen_VarDeclaration(self, node: VarDeclaration):
        self.emit(f"  ALLOC {node.type_node.name} {node.name}")
        if node.initializer:
            val = self.gen_node(node.initializer)
            self.emit(f"  STORE {node.name}, {val}")

    def gen_Assignment(self, node: Assignment) -> str:
        val = self.gen_node(node.value)
        if isinstance(node.target, Identifier):
            if node.op == '=':
                self.emit(f"  STORE {node.target.name}, {val}")
                return node.target.name
            else:
                op_map = {'+=': 'ADD', '-=': 'SUB', '*=': 'MUL', '/=': 'DIV'}
                t = self.new_temp()
                self.emit(f"  {op_map[node.op]} {t}, {node.target.name}, {val}")
                self.emit(f"  STORE {node.target.name}, {t}")
                return t
        return val

    def gen_BinaryOp(self, node: BinaryOp) -> str:
        left = self.gen_node(node.left)
        right = self.gen_node(node.right)
        t = self.new_temp()
        op_map = {
            '+': 'ADD', '-': 'SUB', '*': 'MUL', '/': 'DIV', '%': 'MOD',
            '==': 'EQ', '!=': 'NEQ', '<': 'LT', '<=': 'LTE',
            '>': 'GT', '>=': 'GTE', '&&': 'AND', '||': 'OR',
        }
        op = op_map.get(node.op, node.op)
        self.emit(f"  {op} {t}, {left}, {right}")
        return t

    def gen_UnaryOp(self, node: UnaryOp) -> str:
        operand = self.gen_node(node.operand)
        t = self.new_temp()
        if node.op == '-':
            self.emit(f"  NEG {t}, {operand}")
        elif node.op == '!':
            self.emit(f"  NOT {t}, {operand}")
        elif node.op in ('++', '--'):
            op = 'ADD' if node.op == '++' else 'SUB'
            if node.prefix:
                self.emit(f"  {op} {t}, {operand}, 1")
                if isinstance(node.operand, Identifier):
                    self.emit(f"  STORE {node.operand.name}, {t}")
            else:
                self.emit(f"  COPY {t}, {operand}")
                tmp2 = self.new_temp()
                self.emit(f"  {op} {tmp2}, {operand}, 1")
                if isinstance(node.operand, Identifier):
                    self.emit(f"  STORE {node.operand.name}, {tmp2}")
        return t

    def gen_IfStatement(self, node: IfStatement):
        cond = self.gen_node(node.condition)
        else_label = self.new_label()
        end_label = self.new_label()
        self.emit(f"  JMPF {cond}, {else_label}")
        self.gen_node(node.then_block)
        self.emit(f"  JMP {end_label}")
        self.emit(f"{else_label}:")
        if node.else_block:
            self.gen_node(node.else_block)
        self.emit(f"{end_label}:")

    def gen_WhileStatement(self, node: WhileStatement):
        start = self.new_label()
        end = self.new_label()
        self.emit(f"{start}:")
        cond = self.gen_node(node.condition)
        self.emit(f"  JMPF {cond}, {end}")
        self.gen_node(node.body)
        self.emit(f"  JMP {start}")
        self.emit(f"{end}:")

    def gen_DoWhileStatement(self, node: DoWhileStatement):
        start = self.new_label()
        self.emit(f"{start}:")
        self.gen_node(node.body)
        cond = self.gen_node(node.condition)
        self.emit(f"  JMPT {cond}, {start}")

    def gen_ForStatement(self, node: ForStatement):
        start = self.new_label()
        end = self.new_label()
        if node.init:
            self.gen_node(node.init)
        self.emit(f"{start}:")
        if node.condition:
            cond = self.gen_node(node.condition)
            self.emit(f"  JMPF {cond}, {end}")
        self.gen_node(node.body)
        if node.update:
            self.gen_node(node.update)
        self.emit(f"  JMP {start}")
        self.emit(f"{end}:")

    def gen_ReturnStatement(self, node: ReturnStatement):
        if node.value:
            val = self.gen_node(node.value)
            self.emit(f"  RET {val}")
        else:
            self.emit(f"  RET")

    def gen_BreakStatement(self, node: BreakStatement):
        self.emit(f"  BREAK")

    def gen_ContinueStatement(self, node: ContinueStatement):
        self.emit(f"  CONTINUE")

    def gen_ExprStatement(self, node: ExprStatement):
        self.gen_node(node.expr)

    def gen_FunctionCall(self, node: FunctionCall) -> str:
        args = [self.gen_node(a) for a in node.args]
        t = self.new_temp()
        self.emit(f"  CALL {t}, {node.name}({', '.join(args)})")
        return t

    def gen_PrintfCall(self, node: PrintfCall) -> str:
        args = [self.gen_node(a) for a in node.args]
        self.emit(f"  PRINTF \"{node.format_str}\", [{', '.join(args)}]")
        return "void"

    def gen_ArrayIndex(self, node: ArrayIndex) -> str:
        arr = self.gen_node(node.array)
        idx = self.gen_node(node.index)
        t = self.new_temp()
        self.emit(f"  LOAD_IDX {t}, {arr}[{idx}]")
        return t

    def gen_IntLiteral(self, node: IntLiteral) -> str:
        return str(node.value)

    def gen_FloatLiteral(self, node: FloatLiteral) -> str:
        return str(node.value)

    def gen_CharLiteral(self, node: CharLiteral) -> str:
        return f"'{node.value}'"

    def gen_StringLiteral(self, node: StringLiteral) -> str:
        return f'"{node.value}"'

    def gen_Identifier(self, node: Identifier) -> str:
        return node.name


#  Python Code Generator (backend) 

class PythonCodeGen:
    """
    Translates the AST into runnable Python code.
    This acts as the 'machine code' output — Python is our target runtime.
    """

    def __init__(self):
        self.lines: List[str] = []
        self.indent = 0
        self.temp_count = 0
        self.label_count = 0
        self.string_literals: List[str] = []

    def emit(self, line: str = ""):
        prefix = "    " * self.indent
        self.lines.append(prefix + line if line else "")

    def indented(self):
        class _Ctx:
            def __init__(self_, gen):
                self_.gen = gen
            def __enter__(self_):
                self_.gen.indent += 1
            def __exit__(self_, *_):
                self_.gen.indent -= 1
        return _Ctx(self)

    def generate(self, program: Program) -> str:
        self.emit("# ============================================================")
        self.emit("# Python output from PyCCompiler — do not edit manually")
        self.emit("# ============================================================")
        self.emit("import sys, math")
        self.emit("")
        self.emit("# ── Runtime helpers ──────────────────────────────────────────")
        self.emit("def _printf(fmt, *args):")
        self.emit("    i, ai = 0, 0")
        self.emit("    result = []")
        self.emit("    while i < len(fmt):")
        self.emit("        if fmt[i] == '%' and i+1 < len(fmt):")
        self.emit("            spec = fmt[i+1]")
        self.emit("            if spec == 'd' and ai < len(args): result.append(str(int(args[ai]))); ai += 1")
        self.emit("            elif spec == 'f' and ai < len(args): result.append(f'{float(args[ai]):.6f}'); ai += 1")
        self.emit("            elif spec == 'c' and ai < len(args):")
        self.emit("                v = args[ai]; result.append(chr(v) if isinstance(v,int) else str(v)); ai += 1")
        self.emit("            elif spec == 's' and ai < len(args): result.append(str(args[ai])); ai += 1")
        self.emit("            elif spec == '%': result.append('%')")
        self.emit("            else: result.append(fmt[i:i+2])")
        self.emit("            i += 2")
        self.emit("        else:")
        self.emit("            result.append(fmt[i]); i += 1")
        self.emit("    print(''.join(result), end='')")
        self.emit("")

        for decl in program.declarations:
            self.gen_node(decl)
            self.emit("")

        self.emit("# ── Entry point ──────────────────────────────────────────────")
        self.emit("if __name__ == '__main__':")
        with self.indented():
            self.emit("try:")
            with self.indented():
                self.emit("result = main()")
                self.emit("sys.exit(result if isinstance(result, int) else 0)")
            self.emit("except SystemExit as e:")
            with self.indented():
                self.emit("sys.exit(e.code)")
            self.emit("except Exception as e:")
            with self.indented():
                self.emit("print(f'Runtime error: {e}', file=sys.stderr)")
                self.emit("sys.exit(1)")

        return "\n".join(self.lines)

    def gen_node(self, node: ASTNode) -> str:
        method = f"gen_{type(node).__name__}"
        gen = getattr(self, method, None)
        if gen:
            return gen(node)
        return ""

    def gen_Program(self, node: Program):
        for decl in node.declarations:
            self.gen_node(decl)

    def gen_FunctionDef(self, node: FunctionDef):
        params = ", ".join(p.name for p in node.params)
        self.emit(f"def {node.name}({params}):")
        with self.indented():
            if not node.body.statements:
                self.emit("pass")
            else:
                self.gen_node(node.body)

    def gen_Block(self, node: Block):
        if not node.statements:
            self.emit("pass")
        for stmt in node.statements:
            self.gen_node(stmt)

    def gen_VarDeclaration(self, node: VarDeclaration):
        if node.type_node.array_size is not None:
            # Array declaration
            defaults = {'int': '0', 'float': '0.0', 'char': "'\\x00'"}
            default = defaults.get(node.type_node.name, '0')
            self.emit(f"{node.name} = [{default}] * {node.type_node.array_size}")
        elif node.initializer:
            val = self.gen_expr(node.initializer)
            self.emit(f"{node.name} = {val}")
        else:
            # default values
            defaults = {'int': '0', 'float': '0.0', 'char': "'\\x00'", 'void': 'None'}
            self.emit(f"{node.name} = {defaults.get(node.type_node.name, '0')}")

    def gen_ExprStatement(self, node: ExprStatement):
        # Special-case statements that need direct assignment form
        expr = node.expr
        if isinstance(expr, UnaryOp) and expr.op in ('++', '--'):
            name = self.gen_expr(expr.operand)
            op = '+=' if expr.op == '++' else '-='
            self.emit(f"{name} {op} 1")
        elif isinstance(expr, Assignment):
            self._emit_assignment(expr)
        else:
            self.emit(self.gen_expr(expr))

    def _emit_assignment(self, node: Assignment):
        """Emit assignment as a statement (not expression)."""
        target = self.gen_expr(node.target)
        value = self.gen_expr(node.value)
        if node.op == '=':
            self.emit(f"{target} = {value}")
        else:
            self.emit(f"{target} {node.op} {value}")

    def gen_ReturnStatement(self, node: ReturnStatement):
        if node.value:
            self.emit(f"return {self.gen_expr(node.value)}")
        else:
            self.emit("return None")

    def gen_BreakStatement(self, node: BreakStatement):
        self.emit("break")

    def gen_ContinueStatement(self, node: ContinueStatement):
        self.emit("continue")

    def gen_IfStatement(self, node: IfStatement):
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        with self.indented():
            if isinstance(node.then_block, Block):
                self.gen_Block(node.then_block)
            else:
                self.gen_node(node.then_block)
        if node.else_block:
            self.emit("else:")
            with self.indented():
                if isinstance(node.else_block, Block):
                    self.gen_Block(node.else_block)
                else:
                    self.gen_node(node.else_block)

    def gen_WhileStatement(self, node: WhileStatement):
        cond = self.gen_expr(node.condition)
        self.emit(f"while {cond}:")
        with self.indented():
            if isinstance(node.body, Block):
                self.gen_Block(node.body)
            else:
                self.gen_node(node.body)

    def gen_DoWhileStatement(self, node: DoWhileStatement):
        self.emit("while True:")
        with self.indented():
            if isinstance(node.body, Block):
                self.gen_Block(node.body)
            else:
                self.gen_node(node.body)
            cond = self.gen_expr(node.condition)
            self.emit(f"if not ({cond}): break")

    def gen_ForStatement(self, node: ForStatement):
        if node.init:
            if isinstance(node.init, VarDeclaration):
                self.gen_node(node.init)
            elif isinstance(node.init, Assignment):
                self._emit_assignment(node.init)
            elif isinstance(node.init, ExprStatement):
                expr = node.init.expr
                if isinstance(expr, Assignment):
                    self._emit_assignment(expr)
                else:
                    self.emit(self.gen_expr(expr))
            else:
                self.gen_node(node.init)
        cond = self.gen_expr(node.condition) if node.condition else "True"
        self.emit(f"while {cond}:")
        with self.indented():
            if isinstance(node.body, Block):
                self.gen_Block(node.body)
            else:
                self.gen_node(node.body)
            if node.update:
                upd = node.update
                if isinstance(upd, UnaryOp) and upd.op in ('++', '--'):
                    name = self.gen_expr(upd.operand)
                    op = '+=' if upd.op == '++' else '-='
                    self.emit(f"{name} {op} 1")
                elif isinstance(upd, Assignment):
                    self._emit_assignment(upd)
                else:
                    self.emit(self.gen_expr(upd))

    # Expression generation 

    def gen_expr(self, node: ASTNode) -> str:
        method = f"expr_{type(node).__name__}"
        gen = getattr(self, method, None)
        if gen:
            return gen(node)
        # Fallback — try gen_node style
        return repr(node)

    def expr_IntLiteral(self, node: IntLiteral) -> str:
        return str(node.value)

    def expr_FloatLiteral(self, node: FloatLiteral) -> str:
        return str(node.value)

    def expr_CharLiteral(self, node: CharLiteral) -> str:
        return f"ord({repr(node.value)})"

    def expr_StringLiteral(self, node: StringLiteral) -> str:
        return repr(node.value)

    def expr_Identifier(self, node: Identifier) -> str:
        return node.name

    def expr_BinaryOp(self, node: BinaryOp) -> str:
        left = self.gen_expr(node.left)
        right = self.gen_expr(node.right)
        py_ops = {
            '+': '+', '-': '-', '*': '*', '/': '/', '%': '%',
            '==': '==', '!=': '!=', '<': '<', '<=': '<=',
            '>': '>', '>=': '>=', '&&': 'and', '||': 'or',
        }
        op = py_ops.get(node.op, node.op)
        # Integer division for int / int (C semantics)
        if node.op == '/':
            return f"(int({left}) // int({right}) if isinstance({left}, int) and isinstance({right}, int) else {left} / {right})"
        return f"({left} {op} {right})"

    def expr_UnaryOp(self, node: UnaryOp) -> str:
        if node.op == '-':
            return f"(-{self.gen_expr(node.operand)})"
        if node.op == '!':
            return f"(not {self.gen_expr(node.operand)})"
        if node.op in ('++', '--'):
            delta = '1' if node.op == '++' else '-1'
            name = self.gen_expr(node.operand)
            # emit side-effect separately; return value depends on prefix/postfix
            # We inline it as an expression using a lambda trick for prefix
            if node.prefix:
                return f"(lambda: ({name}.__class__.__name__ and None) or {name} + {delta})()"
            else:
                return f"{name}"  # postfix: value before increment (increment handled as statement)
        return self.gen_expr(node.operand)

    def expr_Assignment(self, node: Assignment) -> str:
        # In expression context (e.g., inside a condition), use walrus for simple =
        target = self.gen_expr(node.target)
        value = self.gen_expr(node.value)
        if node.op == '=':
            return f"({target} := {value})"
        op_map = {'+=': '+', '-=': '-', '*=': '*', '/=': '/'}
        py_op = op_map.get(node.op, node.op[0])
        return f"({target} := {target} {py_op} {value})"

    def expr_FunctionCall(self, node: FunctionCall) -> str:
        args = ", ".join(self.gen_expr(a) for a in node.args)
        return f"{node.name}({args})"

    def expr_PrintfCall(self, node: PrintfCall) -> str:
        args = ", ".join(self.gen_expr(a) for a in node.args)
        if args:
            return f"_printf({repr(node.format_str)}, {args})"
        return f"_printf({repr(node.format_str)})"

    def expr_ArrayIndex(self, node: ArrayIndex) -> str:
        arr = self.gen_expr(node.array)
        idx = self.gen_expr(node.index)
        return f"{arr}[{idx}]"